### ISSUE TITLE
FlyoutItem e MenuItem

### ISSUE THREAD

**Issue by altevircardosoneto** [MonkeyNights/maratona-shell#10]
Eu consigo replicar a parte do Footer similar ao layout da imagem abaixo somente com FlyoutItem e MenuItem?
OBS: Levando em consideração o separador e o espaçamento entre os itens.

![image](https://user-images.githubusercontent.com/11803107/113488416-62e24a00-9494-11eb-995c-fa76e4067d15.png)

**Comment by wsrzx** [comment]
Opa, respondido na live https://www.youtube.com/watch?v=BpZG2d-SPjQ

**Comment by altevircardosoneto** [comment]
boa! @willbuildapps 👊

**Comment by altevircardosoneto** [comment]
@willbuildapps, @angelobelchior , @pictos  vlww pela dica da live, resolvido! 😎

![screenshot-1617480746884](https://user-images.githubusercontent.com/11803107/113490387-e6556880-949f-11eb-93cb-4235888c0280.jpg)
